name: "Okteto Context"
description: "Login into to an Okteto Cloud account"
inputs:
  token: 
    description: "Your okteto API token"
    required: true
  url: 
    description: "Okteto Enterprise URL. Use this to run your actions in your Okteto Enterprise instance (https://okteto.com/enterprise)."
    required: false
  namespace: 
    description: "If present, the namespace you want to point to. If not specified, it will use the default namespace."
    required: false
runs:
  using: "docker"
  image: "Dockerfile"
